---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: portworx-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "2"
  priority_io: high
  io_profile: "auto"
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: px-repl3-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "3"
  priority_io: high
allowVolumeExpansion: true