apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
spec:
  interval: 5m
  chart:
    spec:
      version: 1.8.2
      chart: harbor
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
      interval: 1m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    expose:
      tls:
        certSource: auto
        auto:
          commonName: "harbor.example.lcl"
      ingress:
        hosts:
          core: harbor.example.lcl
          notary: notary.example.lcl
        controller: "ingress-nginx"
    externalURL: https://harbor.example.lcl
    ipFamily:
      ipv6:
        enabled: false
    persistence:
      enabled: true
      resourcePolicy: "keep"
      persistentVolumeClaim:
        registry:
          storageClass: "portworx-sc"
          accessMode: ReadWriteOnce
          size: 5Gi
        chartmuseum:
          storageClass: "portworx-sc"
          accessMode: ReadWriteOnce
          size: 5Gi
        jobservice:
          storageClass: "portworx-sc"
          accessMode: ReadWriteOnce
          size: 1Gi
        database:
          storageClass: "portworx-sc"
          accessMode: ReadWriteOnce
          size: 1Gi
        redis:
          storageClass: "portworx-sc"
          accessMode: ReadWriteOnce
          size: 1Gi
        trivy:
          storageClass: "portworx-sc"
          accessMode: ReadWriteOnce
          size: 5Gi
    database:
      internal:
        password: "Bluecoats91!94!"
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    trivy:
      gitHubToken: ""
