kind: StorageCluster
apiVersion: core.libopenstorage.org/v1
metadata:
  name: ck-homelab
  namespace: kube-system
spec:
  image: portworx/oci-monitor:2.9.1.3
  imagePullPolicy: Always
  kvdb:
    internal: true
  storage:
    devices:
    - /dev/sda
    journalDevice: auto
    kvdbDevice: /dev/nvme0n1p3
  secretsProvider: k8s
  stork:
    enabled: true
    args:
      webhook-controller: "true"
    image: openstorage/stork:2.9.0
  autopilot:
    enabled: true
    providers:
    - name: default
      params:
        url: http://promstack-prometheus.monitoring.svc:9090
      type: prometheus
  monitoring:
    prometheus:
      exportMetrics: true